### ISSUE TITLE
Running inference with kenlm lm

### ISSUE THREAD

**Issue by kamil-bentounes** [Edresson/Wav2Vec-Wrapper#2]
Hello !

I run first a test without kenlm, I got no error. I'm now interested in running an inference using a lm. I generated my own binary lm file using kenlm library, and generate lexicon.lst using your script. When testing, I'm getting the following error:
`> Inference using KenLM`
`Traceback (most recent call last):`
`  File "test.py", line 318, in <module>`
`    kenlm = KenLMDecoder(config.KenLM, vocab_dict, blank=pad_token, silence=silence_token, unk=unk_token)`
`  File "test.py", line 95, in __init__`
`    self.lexicon = load_words(kenlm_args['lexicon_path'])`
`RuntimeError: [loadWords] Invalid line:`

Any help ?

Ubuntu 18.04
Python3.7

**Comment by Edresson** [comment]
Hi, 

This indicates that in your lexicon there is an invalid line. Check if any of the lines in your lexicon are non-standard (eg a blank line)

**Comment by kamil-bentounes** [comment]
Thank's for your fast reply. I checked my file but I will double check it ;)
